python3 get_trajs_drug_res_stats.py None 0.2
python3 get_trajs_drug_res_stats.py None 0.4
python3 get_trajs_drug_res_stats.py None 0.6
python3 get_trajs_drug_res_stats.py None 0.8
python3 get_trajs_drug_res_stats.py None 1.0
python3 get_trajs_drug_res_stats.py IDV 0.2
python3 get_trajs_drug_res_stats.py IDV 0.4
python3 get_trajs_drug_res_stats.py IDV 0.6
python3 get_trajs_drug_res_stats.py IDV 0.8
python3 get_trajs_drug_res_stats.py IDV 1.0
python3 get_trajs_drug_res_stats.py SQV 0.2
python3 get_trajs_drug_res_stats.py SQV 0.4
python3 get_trajs_drug_res_stats.py SQV 0.6
python3 get_trajs_drug_res_stats.py SQV 0.8
python3 get_trajs_drug_res_stats.py SQV 1.0
python3 get_trajs_drug_res_stats.py NFV 0.2
python3 get_trajs_drug_res_stats.py NFV 0.4
python3 get_trajs_drug_res_stats.py NFV 0.6
python3 get_trajs_drug_res_stats.py NFV 0.8
python3 get_trajs_drug_res_stats.py NFV 1.0
python3 get_trajs_drug_res_stats.py RTV 0.2
python3 get_trajs_drug_res_stats.py RTV 0.4
python3 get_trajs_drug_res_stats.py RTV 0.6
python3 get_trajs_drug_res_stats.py RTV 0.8
python3 get_trajs_drug_res_stats.py RTV 1.0
python3 get_trajs_drug_res_stats.py IDV,RTV,SQV 0.2
python3 get_trajs_drug_res_stats.py IDV,RTV,SQV 0.4
python3 get_trajs_drug_res_stats.py IDV,RTV,SQV 0.6
python3 get_trajs_drug_res_stats.py IDV,RTV,SQV 0.8
python3 get_trajs_drug_res_stats.py IDV,RTV,SQV 1.0
python3 get_trajs_drug_res_stats.py RTV,SQV 0.2
python3 get_trajs_drug_res_stats.py RTV,SQV 0.4
python3 get_trajs_drug_res_stats.py RTV,SQV 0.6
python3 get_trajs_drug_res_stats.py RTV,SQV 0.8
python3 get_trajs_drug_res_stats.py RTV,SQV 1.0
python3 get_trajs_drug_res_stats.py IDV,NFV,RTV,SQV 0.2
python3 get_trajs_drug_res_stats.py IDV,NFV,RTV,SQV 0.4
python3 get_trajs_drug_res_stats.py IDV,NFV,RTV,SQV 0.6
python3 get_trajs_drug_res_stats.py IDV,NFV,RTV,SQV 0.8
python3 get_trajs_drug_res_stats.py IDV,NFV,RTV,SQV 1.0
python3 get_trajs_drug_res_stats.py IDV,NFV 0.2
python3 get_trajs_drug_res_stats.py IDV,NFV 0.4
python3 get_trajs_drug_res_stats.py IDV,NFV 0.6
python3 get_trajs_drug_res_stats.py IDV,NFV 0.8
python3 get_trajs_drug_res_stats.py IDV,NFV 1.0
python3 get_trajs_drug_res_stats.py LPV 0.2
python3 get_trajs_drug_res_stats.py LPV 0.4
python3 get_trajs_drug_res_stats.py LPV 0.6
python3 get_trajs_drug_res_stats.py LPV 0.8
python3 get_trajs_drug_res_stats.py LPV 1.0
python3 get_trajs_drug_res_stats.py ATV,RTV 0.2
python3 get_trajs_drug_res_stats.py ATV,RTV 0.4
python3 get_trajs_drug_res_stats.py ATV,RTV 0.6
python3 get_trajs_drug_res_stats.py ATV,RTV 0.8
python3 get_trajs_drug_res_stats.py ATV,RTV 1.0
